# Generated by Django 2.2.1 on 2019-05-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='es_rating',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
