# Generated by Django 2.2.1 on 2019-05-20 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0002_auto_20190519_2101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='establishment',
            options={'verbose_name': 'Estabelecimento', 'verbose_name_plural': 'Estabelecimentos'},
        ),
    ]
