# Generated by Django 2.2.1 on 2019-05-19 17:30

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Tecnologia'), ('2', 'Diversão'), ('3', 'Fotografia'), ('4', 'Gastronomia'), ('5', 'Bons Drinks'), ('6', 'Música'), ('7', 'Moda'), ('8', 'Viagem')], max_length=15)),
            ],
        ),
    ]
