# Generated by Django 2.2.1 on 2019-05-21 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_tiposrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='tipos_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.TiposRole'),
        ),
    ]
