# Generated by Django 2.2.1 on 2019-05-21 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_tiposrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='tipos_role',
            field=models.CharField(choices=[('Música', 'Música'), ('Tecnologia', 'Tecnologia'), ('Gastronomia', 'Gastronomia'), ('Fotografia', 'Fotografia'), ('Moda', 'Moda'), ('Bons Drinks', 'Bons Drinks'), ('Viagem', 'viagem'), ('Diversão', 'Diversão')], max_length=50),
        ),
    ]
