# Generated by Django 2.2.1 on 2019-05-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0003_auto_20190520_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='tipos_role',
            field=models.CharField(choices=[('1', 'Tecnologia'), ('2', 'Diversão'), ('3', 'Fotografia'), ('4', 'Gastronomia'), ('5', 'Bons Drinks'), ('6', 'Música'), ('7', 'Moda'), ('8', 'Viagem')], max_length=50),
        ),
    ]
