# Generated by Django 2.2.1 on 2019-05-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0005_userinterests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinterests',
            name='tipos_role',
            field=models.IntegerField(default=0),
        ),
    ]
