# Generated by Django 2.2.1 on 2019-05-21 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0007_auto_20190521_0807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinterests',
            options={'verbose_name': 'Interesse', 'verbose_name_plural': 'Interesses do Usuário'},
        ),
    ]
