# Generated by Django 2.2.1 on 2019-05-21 12:30

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0008_auto_20190521_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='tipos_role',
            field=models.CharField(choices=[('Tecnologia', 'Tecnologia'), ('Diversão', 'Diversão'), ('Fotografia', 'Fotografia'), ('Gastronomia', 'Gastronomia'), ('Bons Drinks', 'Bons Drinks'), ('Música', 'Música'), ('Moda', 'Moda'), ('Viagem', 'Viagem')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tiposrole',
            name='choices',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Tecnologia', 'Tecnologia'), ('Diversão', 'Diversão'), ('Fotografia', 'Fotografia'), ('Gastronomia', 'Gastronomia'), ('Bons Drinks', 'Bons Drinks'), ('Música', 'Música'), ('Moda', 'Moda'), ('Viagem', 'Viagem')], max_length=73),
        ),
    ]
