# Generated by Django 2.2.1 on 2019-05-21 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0009_auto_20190521_0930'),
        ('role', '0003_auto_20190521_0048'),
    ]

    operations = [
    ]
