# Generated by Django 2.2.1 on 2019-05-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0010_merge_20190521_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='tipos_role',
            field=models.CharField(choices=[('Tecnologia', 'Tecnologia'), ('Diversão', 'Diversão'), ('Fotografia', 'Fotografia'), ('Gastronomia', 'Gastronomia'), ('Bons Drinks', 'Bons Drinks'), ('Música', 'Música'), ('Moda', 'Moda'), ('Viagem', 'Viagem')], max_length=50),
        ),
    ]
