# Generated by Django 2.2.1 on 2019-05-16 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('user_last_name', models.CharField(max_length=255)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_cellphone', models.CharField(max_length=11)),
                ('user_birthday', models.DateField()),
            ],
        ),
    ]
