# Generated by Django 2.2.1 on 2019-05-20 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_cellphone', models.CharField(max_length=11)),
                ('user_birthday', models.DateField()),
                ('tecnologia', models.BooleanField(default=False)),
                ('diversao', models.BooleanField(default=False)),
                ('fotografia', models.BooleanField(default=False)),
                ('gastronomia', models.BooleanField(default=False)),
                ('bons_drinks', models.BooleanField(default=False)),
                ('musica', models.BooleanField(default=False)),
                ('moda', models.BooleanField(default=False)),
                ('viagem', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
