# Generated by Django 2.2.1 on 2019-05-20 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190520_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_birthday',
            field=models.DateField(null=True),
        ),
    ]
