# Generated by Django 2.2.1 on 2019-05-20 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190520_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_birthday',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user_cellphone',
            new_name='cellphone',
        ),
    ]
